version: '3.8'
services:
  app:
    build: .
    container_name: simulation_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command:
